INSERT INTO generos(nombre) VALUES ('Terror');
INSERT INTO generos(nombre) VALUES ('Suspenso');
INSERT INTO generos(nombre) VALUES ('Romance');
INSERT INTO generos(nombre) VALUES ('Policial');
INSERT INTO personajes(nombre, edad, peso, historia) VALUES ('Jacqueline', 26, 55.7, 'Es una actriz canadiense. Protagonizó la serie Salvation de CBS.');
INSERT INTO personajes(nombre, edad, peso, historia) VALUES ('Vera', 86, 70.0, 'Supermodelo que enamoró a Coco Chanel y ahora ha conquistado a Paco Plaza.');
INSERT INTO personajes(nombre, edad, peso, historia) VALUES ('Christian', 35, 79.5, 'Es actor, escritor, director, productor y músico. Trabaja en el teatro, peliculas y televisión.');
INSERT INTO personajes(nombre, edad, peso, historia) VALUES ('Joel', 48, 90.2, 'Es actor, director y guionista australiano conocido por haber participado en la serie televisiva Teh secret life of us.');
INSERT INTO personajes(nombre, edad, peso, historia) VALUES ('Sofia', 29, 69.5, 'Nació en Lauderdale, Florida. Hijan de José F. Daccarett y de Laura Char Canson.');
INSERT INTO personajes(nombre, edad, peso, historia) VALUES ('Jeremy', 52, 80.5, 'Es actor, actor de voz, productor y músico estadounidense.');
INSERT INTO peliculas_series(titulo, fecha_de_creacion, calificacion, genero_id) VALUES ('Chucky', '2004-10-10', 5, 1);
INSERT INTO peliculas_series(titulo, fecha_de_creacion, calificacion, genero_id) VALUES ('Annabelle', '2006-01-10', 2, 1);
INSERT INTO peliculas_series(titulo, fecha_de_creacion, calificacion, genero_id) VALUES ('Jaula', '2021-02-12', 1, 2);
INSERT INTO peliculas_series(titulo, fecha_de_creacion, calificacion, genero_id) VALUES ('Culpable', '2020-07-11', 4, 4);
INSERT INTO peliculas_series(titulo, fecha_de_creacion, calificacion, genero_id) VALUES ('Viejos', '2002-09-05', 4, 2);
INSERT INTO peliculas_series(titulo, fecha_de_creacion, calificacion, genero_id) VALUES ('CODA', '2019-01-03', 3, 3);
INSERT INTO personajes_peliculas_series(personaje_id, pelicula_serie_id) VALUES (1, 1);
INSERT INTO personajes_peliculas_series(personaje_id, pelicula_serie_id) VALUES (2, 2);
INSERT INTO personajes_peliculas_series(personaje_id, pelicula_serie_id) VALUES (3, 3);
INSERT INTO personajes_peliculas_series(personaje_id, pelicula_serie_id) VALUES (4, 5);
INSERT INTO personajes_peliculas_series(personaje_id, pelicula_serie_id) VALUES (5, 4);
INSERT INTO personajes_peliculas_series(personaje_id, pelicula_serie_id) VALUES (6, 6);